### ISSUE TITLE
Error!

### ISSUE THREAD

**Issue by ZeedyPixel** [Dadido3/Pixelcanvas.io-Custom-Client#2]
[19:52:18] [COMPILER] Line 55: GetFullPathName_() is not a function, array, list, map or macro.
[19:52:39] [COMPILER] Line 55: GetFullPathName_() is not a function, array, list, map or macro.

**Comment by Dadido3** [comment]
On which OS are you compiling the client? GetFullPathName is only available on the windows API. I could add a compiler directive with the corresponding function for linux or macOS, but it's not the only function relying on winAPI. I also would need to replace the HTTP post function to make the client work on other OSes.

**Comment by ZeedyPixel** [comment]
Windows x64

**Comment by Dadido3** [comment]
Are you using the demo of PureBasic? The demo is limited to 1000 lines of code and doesn't contain the API functions of any of the OSes. You would need to buy PureBasic to compile the software.

**Comment by ZeedyPixel** [comment]
Yes; I'll see.
