### ISSUE TITLE
XY Coordinates max at 10000

### ISSUE THREAD

**Issue by jdroo** [Dadido3/Pixelcanvas.io-Custom-Client#3]
I can't set a coordinate bigger than 10000, when pixel canvas can go much bigger than that.

also i see no spot for ideas or requests... so, imma put em here too! 

Would be nice if you could just type in the coordinates or something for the viewport instead of dragging forever to move where you want to go.

Maybe a "move to" button to move to a coordinate in the templates.
![40d3255235ccf26b435006550375aa10](https://user-images.githubusercontent.com/13055804/29290201-75367726-80fc-11e7-834a-20823a92ee3d.png)
![200f7b6f918c9be80e23bcdc749479cf](https://user-images.githubusercontent.com/13055804/29290236-8d4400ae-80fc-11e7-9b53-7b7343eb82b0.png)

**Comment by Dadido3** [comment]
Thanks for the suggestions, the limit was from the time when it was very expensive to build far away from center. I changed it and also added some ways to go to coordinates and templates quickly.
