### ISSUE TITLE
Can I Hire You?

### ISSUE THREAD

**Issue by ReActiveMicro** [Dadido3/Pixelcanvas.io-Custom-Client#8]
Nice work Sir!  I would love to see some things added and cleaned up.  Can I hire you?

**Comment by MrCraigTunstall** [comment]
only if you can pay in rupee, and that has to be the Indian rupee, not the Russian one

**Comment by Dadido3** [comment]
I'm interested to see what your business is based on, and why someone would pay any reasonable amount of money for a bot. Especially one for a minimum profit pixel clicking game that's long past its hype.

**Comment by ReActiveMicro** [comment]
It's not for business.  Just for fun and f*uckery.  And I'd much rather learn from someone who knows how things work rather than hire someone from outside.  At the very least let me get an hour of your time to ask a few questions and start to learn some of the things I don't know I don't know.

**Comment by ReActiveMicro** [comment]
Hello Craig.

>I'm interested to see what your business is based on, and why someone
would pay any reasonable amount of money for a bot.

No business.  Just for fun and to make things more simple for me.



>If you have any question about the software itself/how it works/how to
setup everything ask it here, or pm me.

Thanks!  I did want to ask about the captcha.  Your client can tell when it
happens I see.  I assume there are ways around or through it.  You make
mention of this I believe.  Can you explain a little more?  I think this
would be the first issue I address.  I'd like to leave the bot on to
maintain over night, and not wake up to messes each day.




Henry S. Courbis

Office Toll Free: (800) REACTIVE (732-2848)
Office/Mobile Direct: (856) 779-1900
www.ReActiveMicro.com <http://www.ReactiveMicro.com> - Sales, Support, and
News, Our Headquarters on the Internet
ReActiveMicro.com/wiki  - Support, Software, Manuals, and History. Create
your own page today!
Facebook.com/reactivemicrousa - Our Social Media Outlet and Support

**Comment by Dadido3** [comment]
> Your client can tell when it happens I see. I assume there are ways around or through it

The client can't handle captchas yet. It can only see that the "draw pixel" request to the pixelcanvas API failed with some error message.

To make it solve captchas on its own, it would need something like a headless or fake web browser. But it's hard to find one that is compatible with C (So it can work with PureBasic). There are some for C++, but that would need to be wrapped to a C like API. The browser part alone is a bigger project. And then it still needs work to get the captchas and let them solve via some captcha service.

Actually, it would probably be the easiest to write some JavaScript script, that runs in the normal browser. It just needs to check for a captcha, and solve it, if needed.

But as pixelcanvas is effectively dead (Compared to over a year ago), i'm not going to work on it anymore. If it's so important to you, just fire up a few VMs, let each connect over a VPN, and then let it run over night. (That should work if pixelcanvas is still requesting a canvas just every x pixels, and not time based. Idk if that got changed recently)

**Comment by ReActiveMicro** [comment]
Hello Craig.

Thanks for the info.  That will help a lot actually.

Concerning the VM / VPN arrangement, I did read something about SoftEther
VPN.  Is this the correct path to research?




Henry S. Courbis

Office Toll Free: (800) REACTIVE (732-2848)
Office/Mobile Direct: (856) 779-1900
www.ReActiveMicro.com <http://www.ReactiveMicro.com> - Sales, Support, and
News, Our Headquarters on the Internet
ReActiveMicro.com/wiki  - Support, Software, Manuals, and History. Create
your own page today!
Facebook.com/reactivemicrousa - Our Social Media Outlet and Support

**Comment by Dadido3** [comment]
Yes, SoftEther is one of the easier ones to set up and use. And there should be plenty tutorials out there explaining everything.

Btw, craig is another person, not affiliated with this software. Also, could you remove the links and phone numbers below your messages? This is not a place for advertisements.
